---
title: Abdelaziz Njeh
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    location: Post
    breadcrumb:
    - label: Posts
      url: "/"
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: tags
  values:
    tab_active: Tags
    location: Tag
    breadcrumb:
    - label: Home
      url: "/"
    - label: Tags
      url: "/tabs/tags/"
- scope:
    path: categories
  values:
    tab_active: Categories
    location: Category
    breadcrumb:
    - label: Home
      url: "/"
    - label: Categories
      url: "/tabs/categories/"
- scope:
    path: tabs
  values:
    layout: page
    dynamic_title: true
    breadcrumb:
    - label: Home
      url: "/"
- scope:
    path: assets/data
  values:
    layout: compress
tagline: Consultant .NET/Azure/Azure DevOps
description: Hi i am Abdelaziz Njeh
url: https://AzzouzNjah.github.io
author: Abdelaziz Njeh
avatar: "/assets/img/sample/profile.png"
github:
  username: AzzouzNjah
twitter:
  username: AzzouzNjah
social:
  name: Azzouz Njah
  email: njah.abdelaziz@hotmail.com
  links:
  - https://twitter.com/NjahAzzouz
  - https://github.com/azzouznjah
  - https://www.facebook.com/azzouz.njah
  - https://www.linkedin.com/in/abdelaziz-njah
google_site_verification: google_meta_tag_verification
baseurl: 
google_analytics:
  id: 
  pv: false
  proxy_baseurl: 
  proxy_url: 
disqus:
  comments: false
  shortname: 
theme_mode: dual
toc: true
paginate: 10
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: "/posts/:title/"
sass:
  sass_dir: "/assets/css"
  style: compressed
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings:
  - html
  - head
  - body
  - dt
  - dd
  - rt
  - rp
  - optgroup
  - option
  - colgroup
  - caption
  - thead
  - tbody
  - tfoot
  - tr
  - td
  - th
  profile: false
  blanklines: false
exclude:
- vendor
- Gemfile.lock
- Gemfile
- tools
- docs
sitemap_exclude:
  fuzzy:
  - "/assets/"
  accurate:
  - "/norobots/"
  - "/tabs/"
  - "/categories/"
  - "/tags/"
  - "/posts/"
  - 404.html
  - feed.xml
  - sitemap.xml
  - robots.txt
  - redirects.json
plugins:
- jemoji
