---
title: Azzouz Njah.Github.Io
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    location: Post
    breadcrumb:
    - label: Posts
      url: "/"
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: tags
  values:
    tab_active: Tags
    location: Tag
    breadcrumb:
    - label: Home
      url: "/"
    - label: Tags
      url: "/tabs/tags/"
- scope:
    path: categories
  values:
    tab_active: Categories
    location: Category
    breadcrumb:
    - label: Home
      url: "/"
    - label: Categories
      url: "/tabs/categories/"
- scope:
    path: tabs
  values:
    layout: page
    dynamic_title: true
    breadcrumb:
    - label: Home
      url: "/"
- scope:
    path: assets/data
  values:
    layout: compress
